### ISSUE TITLE
Warning while running Trainable Segmentation using scripting API

### ISSUE THREAD

**Issue by mrgloom** [fiji/Trainable_Segmentation#19]
I'm trying to write a script to batch proccess several images.

here it is:

```
//http://imagej.net/Trainable_Weka_Segmentation#Macro_language_compatibility

open("C:\\mage1.png"); //open image

run("Trainable Weka Segmentation"); // then start the plugin

call("trainableSegmentation.Weka_Segmentation.loadClassifier", "C:\\model\\SGD_stack_7.model");

call("trainableSegmentation.Weka_Segmentation.getResult");
```

But result not produced and I get some warning/errors: 

```
Refreshing GOE props...
java.lang.NullPointerException
    at weka.core.ClassCache.initFromManifest(ClassCache.java:248)
    at weka.core.ClassCache.initFromJar(ClassCache.java:293)
    at weka.core.ClassCache.initFromClasspathPart(ClassCache.java:351)
    at weka.core.ClassCache.initialize(ClassCache.java:373)
    at weka.core.ClassCache.<init>(ClassCache.java:111)
    at weka.core.ClassDiscovery.initCache(ClassDiscovery.java:447)
    at weka.core.ClassDiscovery.clearCache(ClassDiscovery.java:481)
    at weka.core.ClassDiscovery.clearClassCache(ClassDiscovery.java:490)
    at weka.core.WekaPackageManager.refreshGOEProperties(WekaPackageManager.java:1143)
    at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1134)
    at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1047)
    at weka.gui.GenericObjectEditor.determineClasses(GenericObjectEditor.java:177)
    at weka.gui.GenericObjectEditor.<clinit>(GenericObjectEditor.java:247)
    at sun.misc.Unsafe.ensureClassInitialized(Native Method)
    at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:25)
    at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:122)
    at java.lang.reflect.Field.acquireFieldAccessor(Field.java:918)
    at java.lang.reflect.Field.getFieldAccessor(Field.java:899)
    at java.lang.reflect.Field.get(Field.java:358)
    at trainableSegmentation.Weka_Segmentation.<clinit>(Weka_Segmentation.java:2362)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at ij.IJ.runUserPlugIn(IJ.java:210)
    at ij.IJ.runPlugIn(IJ.java:176)
    at ij.Executer.runCommand(Executer.java:137)
    at ij.Executer.run(Executer.java:66)
    at ij.IJ.run(IJ.java:292)
    at ij.IJ.run(IJ.java:267)
    at ij.macro.Functions.doRun(Functions.java:603)
    at ij.macro.Functions.doFunction(Functions.java:96)
    at ij.macro.Interpreter.doStatement(Interpreter.java:230)
    at ij.macro.Interpreter.doStatements(Interpreter.java:218)
    at ij.macro.Interpreter.run(Interpreter.java:115)
    at ij.macro.Interpreter.run(Interpreter.java:85)
    at ij.macro.Interpreter.run(Interpreter.java:96)
    at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:155)
    at ij.plugin.Macro_Runner.runMacroFile(Macro_Runner.java:139)
    at ij.plugin.Macro_Runner.run(Macro_Runner.java:35)
    at ij.IJ.runPlugIn(IJ.java:182)
    at ij.Executer.runCommand(Executer.java:137)
    at ij.Executer.run(Executer.java:66)
    at java.lang.Thread.run(Thread.java:662)
java.lang.NullPointerException
    at weka.core.ClassCache.initFromManifest(ClassCache.java:248)
    at weka.core.ClassCache.initFromJar(ClassCache.java:293)
    at weka.core.ClassCache.initFromClasspathPart(ClassCache.java:351)
    at weka.core.ClassCache.initialize(ClassCache.java:373)
    at weka.core.ClassCache.<init>(ClassCache.java:111)
    at weka.core.ClassDiscovery.initCache(ClassDiscovery.java:447)
    at weka.core.ClassDiscovery.clearCache(ClassDiscovery.java:481)
    at weka.core.ClassDiscovery.clearClassCache(ClassDiscovery.java:490)
    at weka.core.WekaPackageManager.refreshGOEProperties(WekaPackageManager.java:1143)
    at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1134)
    at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1047)
    at weka.gui.GenericObjectEditor.determineClasses(GenericObjectEditor.java:177)
    at weka.gui.GenericObjectEditor.<clinit>(GenericObjectEditor.java:247)
    at sun.misc.Unsafe.ensureClassInitialized(Native Method)
    at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:25)
    at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:122)
    at java.lang.reflect.Field.acquireFieldAccessor(Field.java:918)
    at java.lang.reflect.Field.getFieldAccessor(Field.java:899)
    at java.lang.reflect.Field.get(Field.java:358)
    at trainableSegmentation.Weka_Segmentation.<clinit>(Weka_Segmentation.java:2362)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at ij.IJ.runUserPlugIn(IJ.java:210)
    at ij.IJ.runPlugIn(IJ.java:176)
    at ij.Executer.runCommand(Executer.java:137)
    at ij.Executer.run(Executer.java:66)
    at ij.IJ.run(IJ.java:292)
    at ij.IJ.run(IJ.java:267)
    at ij.macro.Functions.doRun(Functions.java:603)
    at ij.macro.Functions.doFunction(Functions.java:96)
    at ij.macro.Interpreter.doStatement(Interpreter.java:230)
    at ij.macro.Interpreter.doStatements(Interpreter.java:218)
    at ij.macro.Interpreter.run(Interpreter.java:115)
    at ij.macro.Interpreter.run(Interpreter.java:85)
    at ij.macro.Interpreter.run(Interpreter.java:96)
    at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:155)
    at ij.plugin.Macro_Runner.runMacroFile(Macro_Runner.java:139)
    at ij.plugin.Macro_Runner.run(Macro_Runner.java:35)
    at ij.IJ.runPlugIn(IJ.java:182)
    at ij.Executer.runCommand(Executer.java:137)
    at ij.Executer.run(Executer.java:66)
    at java.lang.Thread.run(Thread.java:662)
java.lang.NullPointerException
    at weka.core.ClassCache.initFromManifest(ClassCache.java:248)
    at weka.core.ClassCache.initFromJar(ClassCache.java:293)
    at weka.core.ClassCache.initFromClasspathPart(ClassCache.java:351)
    at weka.core.ClassCache.initialize(ClassCache.java:373)
    at weka.core.ClassCache.<init>(ClassCache.java:111)
    at weka.core.ClassDiscovery.clearClassCache(ClassDiscovery.java:492)
    at weka.core.WekaPackageManager.refreshGOEProperties(WekaPackageManager.java:1143)
    at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1134)
    at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1047)
    at weka.gui.GenericObjectEditor.determineClasses(GenericObjectEditor.java:177)
    at weka.gui.GenericObjectEditor.<clinit>(GenericObjectEditor.java:247)
    at sun.misc.Unsafe.ensureClassInitialized(Native Method)
    at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:25)
    at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:122)
    at java.lang.reflect.Field.acquireFieldAccessor(Field.java:918)
    at java.lang.reflect.Field.getFieldAccessor(Field.java:899)
    at java.lang.reflect.Field.get(Field.java:358)
    at trainableSegmentation.Weka_Segmentation.<clinit>(Weka_Segmentation.java:2362)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at ij.IJ.runUserPlugIn(IJ.java:210)
    at ij.IJ.runPlugIn(IJ.java:176)
    at ij.Executer.runCommand(Executer.java:137)
    at ij.Executer.run(Executer.java:66)
    at ij.IJ.run(IJ.java:292)
    at ij.IJ.run(IJ.java:267)
    at ij.macro.Functions.doRun(Functions.java:603)
    at ij.macro.Functions.doFunction(Functions.java:96)
    at ij.macro.Interpreter.doStatement(Interpreter.java:230)
    at ij.macro.Interpreter.doStatements(Interpreter.java:218)
    at ij.macro.Interpreter.run(Interpreter.java:115)
    at ij.macro.Interpreter.run(Interpreter.java:85)
    at ij.macro.Interpreter.run(Interpreter.java:96)
    at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:155)
    at ij.plugin.Macro_Runner.runMacroFile(Macro_Runner.java:139)
    at ij.plugin.Macro_Runner.run(Macro_Runner.java:35)
    at ij.IJ.runPlugIn(IJ.java:182)
    at ij.Executer.runCommand(Executer.java:137)
    at ij.Executer.run(Executer.java:66)
    at java.lang.Thread.run(Thread.java:662)
java.lang.NullPointerException
    at weka.core.ClassCache.initFromManifest(ClassCache.java:248)
    at weka.core.ClassCache.initFromJar(ClassCache.java:293)
    at weka.core.ClassCache.initFromClasspathPart(ClassCache.java:351)
    at weka.core.ClassCache.initialize(ClassCache.java:373)
    at weka.core.ClassCache.<init>(ClassCache.java:111)
    at weka.core.ClassDiscovery.clearClassCache(ClassDiscovery.java:492)
    at weka.core.WekaPackageManager.refreshGOEProperties(WekaPackageManager.java:1143)
    at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1134)
    at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1047)
    at weka.gui.GenericObjectEditor.determineClasses(GenericObjectEditor.java:177)
    at weka.gui.GenericObjectEditor.<clinit>(GenericObjectEditor.java:247)
    at sun.misc.Unsafe.ensureClassInitialized(Native Method)
    at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:25)
    at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:122)
    at java.lang.reflect.Field.acquireFieldAccessor(Field.java:918)
    at java.lang.reflect.Field.getFieldAccessor(Field.java:899)
    at java.lang.reflect.Field.get(Field.java:358)
    at trainableSegmentation.Weka_Segmentation.<clinit>(Weka_Segmentation.java:2362)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at ij.IJ.runUserPlugIn(IJ.java:210)
    at ij.IJ.runPlugIn(IJ.java:176)
    at ij.Executer.runCommand(Executer.java:137)
    at ij.Executer.run(Executer.java:66)
    at ij.IJ.run(IJ.java:292)
    at ij.IJ.run(IJ.java:267)
    at ij.macro.Functions.doRun(Functions.java:603)
    at ij.macro.Functions.doFunction(Functions.java:96)
    at ij.macro.Interpreter.doStatement(Interpreter.java:230)
    at ij.macro.Interpreter.doStatements(Interpreter.java:218)
    at ij.macro.Interpreter.run(Interpreter.java:115)
    at ij.macro.Interpreter.run(Interpreter.java:85)
    at ij.macro.Interpreter.run(Interpreter.java:96)
    at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:155)
    at ij.plugin.Macro_Runner.runMacroFile(Macro_Runner.java:139)
    at ij.plugin.Macro_Runner.run(Macro_Runner.java:35)
    at ij.IJ.runPlugIn(IJ.java:182)
    at ij.Executer.runCommand(Executer.java:137)
    at ij.Executer.run(Executer.java:66)
    at java.lang.Thread.run(Thread.java:662)
[KnowledgeFlow] Loading properties and plugins...
[KnowledgeFlow] Initializing KF...
```

**Comment by iarganda** [comment]
The warning messages are normal and not related to the issue. They are shown the first time you call the plugin. Can you try adding a wait after calling the plugin on your macro? Have a look at this [example on the wiki site](http://imagej.net/Trainable_Weka_Segmentation#Complete_macro_example:).

**Comment by iarganda** [comment]
The warning message were removed on this [commit](https://github.com/fiji/Trainable_Segmentation/commit/686dfddccbacea6199aae686055f18b30d8793d1).
