### ISSUE TITLE
Deadlock when applying classifiers

### ISSUE THREAD

**Issue by ctrueden** [fiji/Trainable_Segmentation#22]
- Open Blobs
- Run Trainable Segmentation
- Load classifier, pick a saved classifier
- Apply classifier, but cancel the dialog box
- Apply classifier again, see deadlock (at least on OS X with Java 8)

```
"pool-3-thread-1":
    at com.apple.laf.AquaFileSystemModel.getRowCount(AquaFileSystemModel.java:194)
    - waiting to lock <0x000000055451c0b8> (a java.lang.Object)
    at javax.swing.JTable.getRowCount(JTable.java:2662)
    at javax.swing.plaf.basic.BasicTableUI.createTableSize(BasicTableUI.java:1692)
    at javax.swing.plaf.basic.BasicTableUI.getPreferredSize(BasicTableUI.java:1733)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
    at javax.swing.ScrollPaneLayout.preferredLayoutSize(ScrollPaneLayout.java:495)
    at java.awt.Container.preferredSize(Container.java:1796)
    - locked <0x000000057d2f6498> (a java.awt.Component$AWTTreeLock)
    at java.awt.Container.getPreferredSize(Container.java:1780)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
    at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
    - locked <0x000000057d2f6498> (a java.awt.Component$AWTTreeLock)
    at java.awt.Container.preferredSize(Container.java:1796)
    - locked <0x000000057d2f6498> (a java.awt.Component$AWTTreeLock)
    at java.awt.Container.getPreferredSize(Container.java:1780)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
    at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
    - locked <0x000000057d2f6498> (a java.awt.Component$AWTTreeLock)
    at java.awt.Container.preferredSize(Container.java:1796)
    - locked <0x000000057d2f6498> (a java.awt.Component$AWTTreeLock)
    at java.awt.Container.getPreferredSize(Container.java:1780)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
    at javax.swing.BoxLayout.checkRequests(BoxLayout.java:484)
    at javax.swing.BoxLayout.layoutContainer(BoxLayout.java:425)
    - locked <0x00000005545061e0> (a javax.swing.BoxLayout)
    at java.awt.Container.layout(Container.java:1510)
    at java.awt.Container.doLayout(Container.java:1499)
    at java.awt.Container.validateTree(Container.java:1695)
    at java.awt.Container.validateTree(Container.java:1704)
    at java.awt.Container.validateTree(Container.java:1704)
    at java.awt.Container.validateTree(Container.java:1704)
    at java.awt.Container.validateTree(Container.java:1704)
    at java.awt.Container.validate(Container.java:1630)
    - locked <0x000000057d2f6498> (a java.awt.Component$AWTTreeLock)
    at java.awt.Container.validateUnconditionally(Container.java:1667)
    - locked <0x000000057d2f6498> (a java.awt.Component$AWTTreeLock)
    at java.awt.Window.pack(Window.java:818)
    at javax.swing.JFileChooser.createDialog(JFileChooser.java:821)
    at javax.swing.JFileChooser.showDialog(JFileChooser.java:749)
    at javax.swing.JFileChooser.showOpenDialog(JFileChooser.java:656)
    at trainableSegmentation.Weka_Segmentation.applyClassifierToTestData(Weka_Segmentation.java:1664)
    at trainableSegmentation.Weka_Segmentation$1$1.run(Weka_Segmentation.java:397)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
"AWT-EventQueue-0":
    at java.awt.Component.invalidate(Component.java:2931)
    - waiting to lock <0x000000057d2f6498> (a java.awt.Component$AWTTreeLock)
    at java.awt.Container.invalidate(Container.java:1587)
    at javax.swing.JComponent.revalidate(JComponent.java:4848)
    at javax.swing.JTable.tableRowsInserted(JTable.java:4482)
    at javax.swing.JTable.tableChanged(JTable.java:4407)
    at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
    at javax.swing.table.AbstractTableModel.fireTableRowsInserted(AbstractTableModel.java:231)
    at com.apple.laf.AquaFileSystemModel$DoChangeContents.run(AquaFileSystemModel.java:458)
    - locked <0x000000055451c0b8> (a java.lang.Object)
    - locked <0x0000000554605060> (a java.lang.Object)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by iarganda** [comment]
It works fine in Linux. I will try later on a Mac.

**Comment by DinaSkp** [comment]
Hi,

Did you find a solution?
I have the same problem, when I try to load the classifier that I've just trained an ‘Error when loading Weka Classifier from file’ opens in a dialog box and nothing load. 
I'm working on Window 7.

Many thanks.

**Comment by iarganda** [comment]
Hello @DinaSkp ,
Did you get any more messages in the log or console window?

**Comment by DinaSkp** [comment]
I get those messages:
'Error while loading classifier'
When I click Ok:
'Error when loading Weka classifier from file'
And in the log:
Error: classifier could not be loaded.

**Comment by iarganda** [comment]
That looks different from the error reported before by @ctrueden. What steps did you follow? Just train, save classifier, load classifier and get the error?

**Comment by DinaSkp** [comment]
Yes. Then I tried after closing and reopening Fiji and I get the same result

**Comment by iarganda** [comment]
I see, can you send me the file so I can reproduce the error, please?

**Comment by DinaSkp** [comment]
The file is to big to be pasted here

**Comment by iarganda** [comment]
Sure, you can use the [Upload Sample Image option in Fiji](http://imagej.net/Upload_Sample_Image) or use any public file sharing system as Google Drive, Dropbox, Mega...

**Comment by DinaSkp** [comment]
Ok! I sent you a Google Drive attachment. Thanks again.

**Comment by iarganda** [comment]
Got it, I can reproduce the error. Can you tell me which version of the plugin you used? Also, what java version are you using?

**Comment by DinaSkp** [comment]
Great! 
I used the 3.2.2 of the plugin and java 7 update 17

**Comment by iarganda** [comment]
Just to be sure, can you try saving and loading the classifier with the latest plugin version (3.2.4)? And maybe java 8 as well?

**Comment by iarganda** [comment]
@ctrueden release 3.2.5 fixes the issue if you deselect the use of JFileChooser in the Input/Output options of Fiji. The bug is related to the JFileChooser issues in Mac OS already reported before by @tpietzsch (see this [post](http://forum.imagej.net/t/register-virtual-stack-slices-plugin-hangs-on-macos/1123/2?u=iarganda) in the Forum).
@DinaSkp I'm going to close this issue. If you still have problems with loading/saving classifiers in Java 8 and the latest plugin version, please open a new issue.
