### ISSUE TITLE
Cannot use Macro to load classifier

### ISSUE THREAD

**Issue by yanningzuo** [fiji/Trainable_Segmentation#31]
Hi,

It seems to be some problems with the "load classifier" macro command. I tried several time with the command as below,but overtime it said "cannot load classifier":

run("Trainable Weka Segmentation");
selectWindow("Trainable Weka Segmentation v3.1.2");
call("trainableSegmentation.Weka_Segmentation.loadClassifier", "/Users/lab-public/Desktop/Green.model");
call("trainableSegmentation.Weka_Segmentation.getProbability");
selectWindow("Probability maps");

I used macro recorder and checked a few times. Probably there's something wrong with the Weka.

Thanks!

**Comment by yanningzuo** [comment]
It says 
Caused by: java.lang.NullPointerException
	at trainableSegmentation.Weka_Segmentation$CustomWindow.setButtonsEnabled(Weka_Segmentation.java:1110)
	at trainableSegmentation.Weka_Segmentation.loadClassifier(Weka_Segmentation.java:2735)

**Comment by yanningzuo** [comment]
Just found it's working on PC

**Comment by iarganda** [comment]
Thanks for reporting! It probably has to do with the dialog to choose the classifier file. I'll fix it as soon as I can.

**Comment by yanningzuo** [comment]
Thank you so much!

Yanning Zuo
Staff Research Associate, Hong Lab

Department of Biological Chemistry
Department of Neurobiology
David Geffen School of Medicine
University of California, Los Angeles

**Comment by iarganda** [comment]
It seems it is a known problem of the open dialog system. Can you please try again after selecting the "Use JFileChooser to open/save" option in the _Edit > Options > Input/Output..._ menu?

It should look like this:
![screenshot from 2016-09-21 16 06 52](https://cloud.githubusercontent.com/assets/4041131/18714261/7ca991ac-8015-11e6-93d1-fb4a0fedc105.png)

**Comment by iarganda** [comment]
@yanningzuo Did you finally test if my proposed solution fixed the issue?

**Comment by yanningzuo** [comment]
Hi Ignacio,

Very sorry for the late reply... I was using PC and I just confirmed that
Mac still couldn't open classifier after selecting the "Use JFileChooser to
open/save" and using version 3.2.4.

Thank you so much for reminding me!

Best regards,

Yanning

Yanning Zuo
Staff Research Associate, Hong Lab

Department of Biological Chemistry
Department of Neurobiology
David Geffen School of Medicine
University of California, Los Angeles

**Comment by iarganda** [comment]
Hello @yanningzuo,
It works the other way around. If you are using a Mac, you should uncheck the "Use JFileChooser to open/save" option. It seems there is a problem with JFileChooser on Mac OS.

**Comment by yanningzuo** [comment]
Hi Ignacio,

I actually tried both ways but neither worked on Mac...

**Comment by iarganda** [comment]
Weird! Which version of Mac OS and Java do you have?

**Comment by yanningzuo** [comment]
I am using OS X Yosemite 10.10.5 and did not install Java on my Mac

**Comment by iarganda** [comment]
I just noticed you are not using version 3.2.5 which enforces the use of other dialogs instead of JFileChooser if the option is unchecked. Can you please try with that version of the plugin?

**Comment by yanningzuo** [comment]
Actually, I am using the latest version 3.2.5 updated today. I remember it
was 3.2.4 last night

This is my most recent code:

selectWindow("Result of Clipboard-1");
run("Trainable Weka Segmentation");
selectWindow("Trainable Weka Segmentation v3.2.5");
call("trainableSegmentation.Weka_Segmentation.loadClassifier",
"/Users/lab-public/Desktop/Green.model");
call("trainableSegmentation.Weka_Segmentation.getProbability");

**Comment by iarganda** [comment]
I see, and this only happens from a macro? You might need to add a `wait` command after calling the plugin so it has time to load. This works for me:
```java
selectWindow("Result of Clipboard-1");
run("Trainable Weka Segmentation");
wait( 2000 );
selectWindow("Trainable Weka Segmentation v3.2.5");
call("trainableSegmentation.Weka_Segmentation.loadClassifier", "/Users/lab-public/Desktop/Green.model");
call("trainableSegmentation.Weka_Segmentation.getProbability");
```
