### ISSUE TITLE
Exception in RandError

### ISSUE THREAD

**Issue by AminSuzani** [fiji/Trainable_Segmentation#6]
Hi,

I tried the sample beanshell script for the rand error, but I get an error all the time. here is my code:
```
import trainableSegmentation.metrics.RandError;
import ij.IJ;
 
// original labels
originalLabels = IJ.openImage("data/A.tiff");
  
// proposed (new) labels
proposedLabels = IJ.openImage("data/B.tiff");
   
// threshold to binarize labels
threshold = 0.5;
 
metric = new RandError( originalLabels, proposedLabels );
randError = metric.getMetricValue( threshold );
     
IJ.log("Rand error between source image " + originalLabels.getTitle() + " and target image "
    + proposedLabels.getTitle() + " = " + randError);
``` 
A.tiff and B.tiff are two simple images where half of each of them is black and the rest is white. I tried different combinations of input images, but got the same error. I use the command `java bsh.Interpreter randErrorTest.java`. Here is the error I got:
```
Error when calculating rand error in a concurrent way.
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: util/FindConnectedRegions
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at trainableSegmentation.metrics.RandError.getMetricValue(RandError.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at bsh.Reflect.invokeMethod(Unknown Source)
	at bsh.Reflect.invokeObjectMethod(Unknown Source)
	at bsh.Name.invokeMethod(Unknown Source)
	at bsh.BSHMethodInvocation.eval(Unknown Source)
	at bsh.BSHPrimaryExpression.eval(Unknown Source)
	at bsh.BSHPrimaryExpression.eval(Unknown Source)
	at bsh.BSHAssignment.eval(Unknown Source)
	at bsh.Interpreter.eval(Unknown Source)
	at bsh.Interpreter.source(Unknown Source)
	at bsh.Interpreter.main(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: util/FindConnectedRegions
	at trainableSegmentation.utils.Utils.connectedComponents(Utils.java:63)
	at trainableSegmentation.metrics.RandError.randError(RandError.java:460)
	at trainableSegmentation.metrics.RandError$2.call(RandError.java:374)
	at trainableSegmentation.metrics.RandError$2.call(RandError.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: util.FindConnectedRegions
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 8 more
Rand error between source image A.tiff and target image B.tiff = 0.0
```
Does anyone know how to fix this?

**Comment by ctrueden** [comment]
@AminSuzani Presumably you are referring to [the Rand_error wiki page](http://fiji.sc/Rand_error)?

Note that BeanShell scripts given on the ImageJ wiki are intended to be executed from within the ImageJ Script Editor. File > New > Script, or press `[`, then choose BeanShell from the Language menu. If you try to run the script using `java bsh.Interpreter`, there will be a couple of problems:
* The SciJava script framework will not be used to populate input parameters, if any (not applicable to this specific script, though).
* You will have to configure your classpath manually.

In this case, you need `util.FindConnectedRegions` which is part of `VIB-lib`. You didn't specify how you set your classpath, but you must not have included `VIB-lib`. I would strongly suggest not trying to run ImageJ BeanShell scripts that way, but instead do it through the Script Editor, or using the [ImageJ launcher from the CLI](http://imagej.net/Headless#Running_scripts_in_headless_mode).

**Comment by ctrueden** [comment]
Closing as invalid, but please reopen if you continue to have trouble with the approaches recommended above. Also note that the ImageJ wiki, being a wiki, welcomes contributions from the community. If you want to spiff up the Rand_error page to avoid future confusion, that would be awesome.

**Comment by AminSuzani** [comment]
Thanks. It works inside the ImageJ.
