### ISSUE TITLE
Tests fail again with ImageJ 1.53u

### ISSUE THREAD

**Issue by ctrueden** [fiji/Trainable_Segmentation#75]
```
$ mvn -Dij.version=1.53u clean test
...
[ERROR] Tests run: 4, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 13.356 s <<< FAILURE! - in trainableSegmentation.BasicTest
[ERROR] bridge(trainableSegmentation.BasicTest)  Time elapsed: 13.129 s  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<490>
	at trainableSegmentation.BasicTest.bridge(BasicTest.java:81)

[ERROR] testDefaultFeatureGenerationMT(trainableSegmentation.BasicTest)  Time elapsed: 0.13 s  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<3055>
	at trainableSegmentation.BasicTest.testDefaultFeaturesOnNuclei(BasicTest.java:105)
	at trainableSegmentation.BasicTest.testDefaultFeatureGenerationMT(BasicTest.java:91)

[ERROR] testDefaultFeatureGenerationST(trainableSegmentation.BasicTest)  Time elapsed: 0.085 s  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<3055>
	at trainableSegmentation.BasicTest.testDefaultFeaturesOnNuclei(BasicTest.java:105)
	at trainableSegmentation.BasicTest.testDefaultFeatureGenerationST(BasicTest.java:86)
```

@hinerm wrote:
> looks like we just need to re-generate the outputs by running the `BasicTest` main method, after updating to a pom-scijava with a 1.53u dep

**Comment by ctrueden** [comment]
Fixed by ff41b4f5a9d38bdad83b493345e12097924e7eeb.
